## custom names should only use hyphens, never use underscores

val_test_frac: .25
bootstrap_repetitions: 100

seeds: [0, 1, 2,]
sample_sizes: [10, 20, 30]

experiments:
  example_regression:
    dataset: "example-dataset"
    features: ["example-features-a","example-features-b"]
    features_cni: ["example-covariates-of-no-interest",]
    targets: ["example-targets",]
    targets_cni: ["none",]
    matching: ["none",]
    models: ["ridge-reg",]
    grid: "default"
  example_classification:
    dataset: "example-dataset"
    features: ["example-features-b"]
    features_cni: ["none",]
    targets: ["example-targets",]
    targets_cni: ["none",]
    matching: ["none",]
    models: ["ridge-cls",]
    grid: "default"


custom_datasets:
  example-dataset:
    features: {'example-features-a':'example/x_a.csv','example-features-b':'example/x_b.csv',}
    targets: {'example-targets':'example/y.csv',}
    covariates: {'example-covariates-of-no-interest':'example/cni.csv',}
