val_test_frac: .25
val_test_min: False
val_test_max: False
bootstrap_repetitions: 100
stratify: False

seeds: [0, 1, 2]
sample_sizes: [128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]

experiments:
  mnist_benchmark:
    dataset: "mnist"
    features: ["pixel",]
    features_cni: ["none",]
    targets: ["ten-digits",]
    targets_cni: ["none",]
    matching: ["none",]
    models: ["ridge-cls",]
    grid: "default"

custom_datasets: {}
