name: esce-dev
channels:
  - conda-forge
dependencies:
  - python
  - scikit-learn
  - pandas
  - scipy
  - imbalanced-learn
  - plotly
  - python-kaleido
  - pip
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  - pyyaml
  - black
  - h5py
  - pip:
    - ruff
