name: esce-dev
channels:
  - conda-forge
dependencies:
  - python
  - scikit-learn
  - pandas
  - scipy
  - imbalanced-learn
  - plotly
  - python-kaleido
  - pip
  - pytest
  - pytest-cov
  - flake8==4.0.1
  - sphinx>=1.8
  - sphinx_rtd_theme
  - sphinx-copybutton
  - piccolo-theme
  - pyyaml
  - black
  - h5py
  - pip:
    - ruff
    - -e ./
