[tool.poetry]
name = "esce"
version = "0.1.2"
description = "Tools for eastimating and extrapolating learning curves."
authors = ["Marc-Andre Schulz <marc-andre.schulz@charite.de>"]
license = "GPLv3" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.2"  
scikit-learn = "^0.24.2"  
pandas = "^1.3.2"
scipy = "^1.7.1"
imbalanced-learn = "^0.8.0"
plotly = "^5.3.1"
kaleido = "0.2.1"  
pyyaml = "^5.4.1"
snakemake = "^6.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
black = "^21.8b0"
flake8 = "^3.9.2"
sphinx = "^4.1.2"
sphinx_rtd_theme = "^0.5.2"


[tool.pytest.ini_options]
norecursedirs = ".snakemake"
