[tool.poetry]
name = "esce"
version = "0.1.2"
description = "Tools for eastimating and extrapolating learning curves."
authors = ["Marc-Andre Schulz <marc-andre.schulz@charite.de>"]
license = "GPLv3" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.7"
scikit-learn = "^0.24.2"  # updated version
numpy = "^1.19.5"
pandas = "^0.24.2"
scipy = "^1.2.1"
imbalanced-learn = "^0.4.3"
plotly = "^3.10.0"
kaleido = "^0.2.1"
pyyaml = "^5.1"
snakemake = "^5.4.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6.0"
pytest-cov = "^2.7.1"
black = "^19.3b0"
flake8 = "^3.7.0"
sphinx = "^1.8.5"
sphinx_rtd_theme = "^0.4.3"

[tool.pytest.ini_options]
norecursedirs = ".snakemake"
