{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "val_test_frac": {
      "type": "number",
      "minimum": 0,
      "maximum": 1,
      "default": 0.25
    },
    "val_test_min": {
      "anyOf": [
        { "type": "boolean", "const": false },
        { "type": "integer", "minimum": 1 }
      ],
      "default": false
    },
    "val_test_max": {
      "anyOf": [
        { "type": "boolean", "const": false },
        { "type": "integer", "minimum": 1 }
      ],
      "default": false
    },
    "bootstrap_repetitions": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5000,
      "default": 100
    },
    "stratify": {
      "type": "boolean",
      "default": false
    },
    "seeds": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0
      },
      "default": [0]
    },
    "sample_sizes": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 1
      },
      "default": [128, 256, 512, 1024, 2048, 4096]
    },
    "experiments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "dataset": {
            "type": "string"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "targets": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "confound_correction_method": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["correct-x", "correct-y", "correct-both", "matching", "with-cni", "only-cni", "none"]
            },
            "minItems": 1,
            "uniqueItems": true
          },
          "confound_correction_cni": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "balanced": {
            "type": "boolean",
            "default": false
          },
          "models": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "grid": {
            "type": "string"
          }
        },
        "required": ["dataset", "features", "targets", "confound_correction_method", "confound_correction_cni", "models", "grid"]
      }
    },
    "custom_datasets": {
      "type": "object",
      "propertyNames": {"pattern": "^[^_]*$"},
      "additionalProperties": {
        "type": "object",
        "properties": {
          "features": {
            "type": "object",
            "propertyNames": {"pattern": "^[^_]*$"},
            "additionalProperties": {
              "type": "string"
            }
          },
          "targets": {
            "type": "object",
            "propertyNames": {"pattern": "^[^_]*$"},
            "additionalProperties": {
              "type": "string"
            }
          },
          "covariates": {
            "type": "object",
            "propertyNames": {"pattern": "^[^_]*$"},
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": ["features", "targets", "covariates"]
      }
    }
  },
  "required": ["val_test_frac", "bootstrap_repetitions", "seeds", "sample_sizes", "experiments", "custom_datasets"]
}
