val_test_frac: .5
val_test_max: 1000
bootstrap_repetitions: 100
stratify: True

seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
sample_sizes: [128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]

experiments: {}

# experiments:
  # mnist_benchmark:
  #   dataset: "mnist"
  #   features: ["pixel",]
  #   features_cni: ["raw",]
  #   targets: ["ten-digits","odd-even"]
  #   targets_cni: ["raw",]
  #   matching: ["none",]
  #   models: ["ridge-cls",]
  #   grid: "default"
  # another_set_of_experiments:
  #   dataset: "mnist"
  #   features: ["pixel",]
  #   features_cni: ["raw",]
  #   targets: ["ten-digits","odd-even"]
  #   targets_cni: ["raw",]
  #   matching: ["none",]
  #   models: ["ridge-cls",]
  #   grid: "default"


custom_datasets: {}

# custom_datasets:
  # dataset_name:
  #   features: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   targets: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   covariates: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  # another_dataset_name:
  #   features: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   targets: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   covariates: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
