val_test_frac: .25
val_test_min: False
val_test_max: False
bootstrap_repetitions: 100
stratify: False

seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
sample_sizes: [128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]

experiments: {}

# experiments:
  # mnist_benchmark:
  #   dataset: "mnist"
  #   features: ["pixel",]
  #   targets: ["ten-digits","odd-even"]
  #   confound_correction_method: ["correct-x", "correct-y", "correct-both", "none"]
  #   confound_correction_cni: ["example-covariates-of-no-interest"]
  #   balanced: false
  #   models: ["ridge-cls",]
  #   grid: "default"
  # another_set_of_experiments:
  #   [...]

custom_datasets: {}


## custom names should only use hyphens, never use underscores
# custom_datasets:
  # dataset_name:
  #   features: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   targets: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   covariates: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  # another_dataset_name:
  #   features: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   targets: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
  #   covariates: {'NAME':'PATH_TO_CSV_TSV_NPY','NAME':'PATH_TO_CSV_TSV_NPY']
