# style parameters for visualisations

extrapolate_to: 100000

figure_titles:
  individual: "{features} vs {targets}; confound correction={confound_correction_method}; cni={confound_correction_cni}; {model}"
  features: "all-features vs {targets}; confound correction={confound_correction_method}; cni={confound_correction_cni}; {model}"
  targets: "{features} vs all-targets; confound correction={confound_correction_method}; {model}"
  models: "{features} vs {targets}; confound correction={confound_correction_method}"
  cni: "{features} vs {targets}; {model}; confound correction={confound_correction_method}"
  hyperparameters: "best hyperparameters - {features} vs {targets}; confound correction={confound_correction_method}; cni={confound_correction_cni}; {model}"

hyperparameter_scales:
# by default linear, can be turned to log scale here
  'alpha': 'log'
  # Add other hyperparameters and their scales