name: Manual workflow

on:
  workflow_dispatch: {}

jobs:
  additional_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: Bhacaz/checkout-files@v2
      with:
        branch: ${{ github.head_ref || github.ref_name }}
        files: tests example

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        auto-activate-base: true

    - name: Install Snakemake with Mamba
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge snakemake

    - name: Run snakemake submodule test (slow)
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        snakemake -s tests/snakefile_submodule -c1 --use-conda

